sudo: required
language: node_js
node_js:
  - "8.11.2"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
env:
  global:
  - CC_TEST_REPORTER_ID=a9114cf0437121f07a35d744703589d3996e341101052b39983a0e8221a4a7b1
  - NODE_ENV=production
  - SECRET_KEY=GROWING@ANDELA
before_script:
  - npm install
  - npm install mocha-lcov-reporter --save-dev
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql -c 'drop database if exists store_manager;' -U postgres
  - psql -c 'create database store_manager;' -U postgres
script:
  - nyc --reporter=lcov npm run test

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit code $TRAVIS_TEST_RESULT